language: node_js
dist: focal
os: linux
node_js:
  - v18.2.0
branches:
  only:
    - main
    - staging
# Install npm dependencies
install:
  - npm ci
services:
  - docker
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy_to_cc.sh
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(main|staging)$"
